Nicer script, using readlink etc

diff --git a/verify-config-path-absolute b/verify-config-path-absolute
--- a/verify-config-path-absolute
+++ b/verify-config-path-absolute
@@ -1,32 +1,39 @@
 #!/bin/sh
+# sh to be compatible
 
 # Goal: We need to edit ini file to change some relative pateches into absolute path.
 # Purpose: this is needed as part of verify-build for example.
 # Tool: sed.  Will use expressions like: s/releaseDir="\.\./releaseDir="\/home\/fn_verify\/01453/
 
 # *** First get absolute path to freenet installation that is 1-level up form location of this script (../)
-this_script_filename=`realpath $0` 
+this_script_filename=`readlink -f $0` 
 this_script_dir=`dirname ${this_script_filename}`
-freenet_dir=`realpath "${this_script_dir}/../"` # 1 above
+freenet_dir=`readlink -f "${this_script_dir}/../"` # 1 above
 
 # Escape for sed string. Replae "/" with "\/". But "\\/" because sed-escaped, "\\\\/" because bash
 freenet_dir_escapedsed=`echo "$freenet_dir" | sed -e 's|/|\\\\/|g'`
 
+script_error() {
+	echo "ERROR: This script had an error - read messages above, exiting"
+	exit 1;
+}
 
 # replacing new-style (since https://github.com/freenet/scripts/commit/cf97427331c8c2bc8ecf870e45decd3b46a1f313)
-for varname in "freenetRoot"
+for varname in "freenetRoot" # loop just used for identical syntax and in case more are needed
 do
 	expr1='s/'; expr2='=".*'; expr3='="'; expr4='"/'  # replace entire line
 	expr="${expr1}${varname}${expr2}/${varname}${expr3}${freenet_dir_escapedsed}${expr4}"; 
-	sed -e "$expr" ~/.freenetrc > ~/.freenetrc-absolute ; mv ~/.freenetrc-absolute ~/.freenetrc
+	sed -e "$expr" ~/.freenetrc > ~/.freenetrc-absolute || script_error 
+	mv ~/.freenetrc-absolute ~/.freenetrc || script_error
 	# e.g.: sed -e 's/fredDir="\.\./fredDir="\/home\/fn_verify\/01453/' /home/fn_verify/.freenetrc
 done
 
-for varname in "releaseDir" "fredDir" # replacing old style (up to 1453)
+for varname in "releaseDir" "fredDir" # replacing old style (up to 1453) so you can verify old builds
 do
 	expr1='s/'; expr2='="\.\.'; expr3='="'; expr4='/' 
 	expr="${expr1}${varname}${expr2}/${varname}${expr3}${freenet_dir_escapedsed}${expr4}"; 
-	sed -e "$expr" ~/.freenetrc > ~/.freenetrc-absolute ; mv ~/.freenetrc-absolute ~/.freenetrc
+	sed -e "$expr" ~/.freenetrc > ~/.freenetrc-absolute || script_error
+	mv ~/.freenetrc-absolute ~/.freenetrc || script_error
 	# e.g.: sed -e 's/fredDir="\.\./fredDir="\/home\/fn_verify\/01453/' /home/fn_verify/.freenetrc
 done
 
