Add error message for freenet.jar fetch failure.

diff --git a/verify-build b/verify-build
--- a/verify-build
+++ b/verify-build
@@ -161,6 +161,10 @@ fi
 # Check that the website and hosted versions are identical.
 # TODO: Detect update USK from node config; configurable node host/port.
 fcpget "SSK@sabn9HY9MKLbFPp851AO98uKtsCtYHM9rqB~A5cCGW4,3yps2z06rLnwf50QU4HvsILakRBYd4vBlPtLv0elUts,AQACAAE/jar-${BUILD}" inserted-freenet.jar
+if [ ! -e "inserted-freenet.jar" ]; then
+    echo "Unable to fetch freenet.jar from Freenet."
+    exit 12
+fi
 if ! cmp freenet.jar inserted-freenet.jar; then
     echo FAILED TO VERIFY: The freenet.jar from the website and the
     echo freenet.jar fetched from Freenet are different.
